### ISSUE TITLE
[BUG] Multiple struct with same field names cause wrong TEAL (confused) code

### ISSUE THREAD

**Issue by 1m1-github** [tinymanorg/tealish#86]
**Describe the bug**
Multiple `struct` with same field names cause wrong `TEAL` (confused) code

```
struct StructA:
 fieldname: int
 q: int
end

struct StructB:
 r: int
 fieldname: int
end

block main:
    StructA a = itob(1)
    int x = a.fieldname
end
```

results in 

```
// block main
main:
  // StructA a = itob(1) [slot 0]
  pushint 1
  itob
  store 0 // a
  // int x = a.fieldname [slot 1]
  load 0 // a
  pushint 8
  extract_uint64 // fieldname
  store 1 // x
```

because `fieldname` is in a different place in the different structs

(the `pushint 8` is wrong in the TEAL code, should be `pushint 0` since `fieldname` is the first field in `StructA`

**To Reproduce**
code above

**Expected behavior**
perhaps field names need the struct name as a prefix to differentiate

**Additional context**

**Comment by fergalwalsh** [comment]
Thanks for reporting. The fields lookup was accidentally scoped to the struct node class instead of the struct instance in the compiler so it same named fields overwrote the previous instance.
I have fixed this in #87 and merged to main.
